services:
  db:
    image: postgres:latest
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wallet_api
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=wallet_db
      - DATABASE_USER=wallet_user
      - DATABASE_PASSWORD=wallet_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

volumes:
  postgres_data:
